[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ers-sdk"
version = "2.8.0"
dependencies = ["PyJWT", "cryptography", "requests", "pyVmomi"]

[project.optional-dependencies]
aws = ["boto3"]

[project.scripts]
ers-cli = "ers_cli:main"
ers-system-test = "ers_system_test:main"
ers-scale-test = "ers_scale_test:main"

[tool.setuptools]
py-modules = ["ers_cli", "ers_system_test", "ers_scale_test"]

[tool.setuptools.packages.find]
include = ["ers", "ers.*", "system_tests", "system_tests.*"]
